# Mosquitto MQTT broker — CTF challenge config

listener 1883
protocol mqtt

# Kjør som root i container-miljø
user root

# Anonym tilkobling er tillatt (realistisk OT-feil)
allow_anonymous true

# Passord- og tilgangskontrollfiler
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

# Logging
log_type all
